# Override resource names
nameOverride: "mcaptcha"
fullnameOverride: "mcaptcha"

# ---------------------------------
# Values associated with deployment
# ---------------------------------

deployment:
  annotations:
    imageregistry: "mcaptcha/mcaptcha"

  env:
    - name: DATABASE_URL
      value: "postgres"
    - name: MCAPTCHA_REDIS_URL
      value: "redis"
    - name: RUST_LOG
      value: "debug"
    - name: PORT
      value: "7000"

  image:
    repository: mcaptcha/mcaptcha
    pullPolicy: Always
    tag: "latest"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# -----------------------------------
# Values associated with certificate
# -----------------------------------

certificate:
  host: captcha.stape.io

# -----------------------------------
# Values associated with ingressRoute
# -----------------------------------

ingressRoute:
  enabled: true
  basicAuth:
    enabled: true
  tls:
    enabled: true


# --------------------------
# Values associated with HPA
# --------------------------

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 100

# ----------------------------------
# Values associated with broadcaster
# ----------------------------------

broadcaster:
  image:
    repository: "europe-west1-docker.pkg.dev/gtm-server-69/stape"
    tag: "62b4bbd"
