{{- if .Values.ingressRoute.basicAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    removeHeader: true
    secret: {{ template "app.fullname" . }}-basic-auth
{{- end }}
