{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- if  .Values.serviceAccount.extraLabels -}}
      {{- toYaml .Values.serviceAccount.extraLabels | nindent 4 -}}
    {{- end -}}
  {{ template "app.serviceAccount.annotations" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
