apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: broadcaster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: broadcaster
subjects:
  - kind: ServiceAccount
    name: broadcaster
    namespace: {{ .Release.Namespace }}
