apiVersion: v1
kind: Service
metadata:
  name: broadcaster
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: broadcaster
  type: ClusterIP
