name: Build Docker Image and Push to GAR

run-name: Build mCaptcha image by @${{ github.actor }}

on:
  push:
    branches:
      - stape

jobs:
  build-and-push:
    name: Build Docker Image and Push to GAR
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    env:
      REGISTRY: ${{ secrets.REGISTRY }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      IMAGE: ${{ secrets.IMAGE }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.run_id }}-${{ github.run_attempt }}
